# These are the settings used to connect to the cloudfactory server

# By default, all operations are done on cloudfactory production
default:
  api_url: "http://cloudfactory.com/api/"
  api_version: "v1"

development:
  api_url: "http://lvh.me:3000/api/"
  api_version: "v1"

production:
  api_url: "http://cloudfactory.com/api/"
  api_version: "v1"

